const cartActionTypes = {
  TOGGLE_CART: 'TOGGLE_CART',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM: 'CLEAR_ITEM',
  CLEAR_CART: 'CLEAR_CART',
  ON_PURCHASE_SUCCESS: 'ON_PURCHASE_SUCCESS',
  ON_PURCHASE_FAILURE: 'ON_PURCHASE_FAILURE'
}

export default cartActionTypes
